packages:
  - "packages/*"
  - "e2e"
  - "website"
  - "!packages/http-client-csharp/**"
  - "!packages/http-client-java/**"
  - "!packages/http-client-python/**"

overrides:
  "cross-spawn@>=7.0.0 <7.0.5": "^7.0.5"
  rollup: 4.49.0 # Regression in 4.50.0 https://github.com/rollup/rollup/issues/6099
  "@alloy-js/csharp": https://pkg.pr.new/alloy-framework/alloy/@alloy-js/csharp@300
